# -*- coding: utf-8 -*-
"""whatsapp automation.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1mEhJw4yoDalDGRpZcJB6MEga1oZAuuUH
"""

pip install twilio

import twilio

from twilio.rest import Client

account_sid = 'ACad34f9127a1ceda3d2c5a21e36045434'
auth_token =  '5b5543cce134fd38b658053dffb74c6d'
client = Client(account_sid, auth_token)

message = client.messages.create(
    body = 'Hey, I am Pallavi here. Hello from Paython, Good Morning, Have a Nice Day',
    from_ = '+18565563092',
to =  '+918698962280')

print(message.sid)